from user import User

from credentials import Credentials

def createUser(username,password):
  '''
  createUser method creates an instance of class User
  '''
  new_user = User(username,password)
  return new_user

def saveUser(user):
  '''
  saveUser method saves the new user instance in user_list array
  '''
  User.saveUser(user)

def checkUser(username,password):
  '''
  checkUser method verifies whether user credentials are correct to login
  '''
  isUser = User.userExists(username,password)
  return isUser

def createCred(userAccount,userSite,password):
  '''
  method will create an instance of credentials
  '''
  new_cred = Credentials(userAccount,userSite,password)

def saveCred(cred):
  '''
  method used to save credential to credentials list
  ''' 
  Credentials.saveCredential(cred)

def generatePassword():
  '''
  method used to generate a random password
  '''
    symbol = 0
    lower = 0
    upper = 0
    number = 0
    count = 0
    password = []

    length = input("Hey, Welcome.How many characters do you want in your password? (default 8)\n")
    length = 8 if length is '' else int(length)

    while count < length:
        rand = random.randint (0,3)
        if rand == 0:
            lower += 1
            b = int(random.randint (97,123))
            password.append(b)
        elif rand == 1:
            upper += 1
            b = random.randint (65,91)
            password.append(b)
        elif rand == 2:
            number += 1
            b = random.randint (48,58)
            password.append(b)
        elif rand == 3:
            r = random.randint(0,2)
            symbol += 1
            if r == 0:
                b = random.randint (33,48)
                password.append(b)
            elif r == 1:
                b = random.randint (91,97)
                password.append(b)
            elif r == 2:
                b = random.randint (123,126)
                password.append(b)
        count +=

    word = "".join([chr(c) for c in password])

    pyperclip.copy(word)

    print ("Random password is \n")
    print(word)

def login():
  '''
  login method verifies whether a user can login
  '''
  username = input("Please enter your username: \n")
  password = input("Please enter your password: \n")
  isUser = checkUser(username,password)
  if(isUser):
    menu()
  else:
    print("Incorrect username or password")
    login()

def register():
  '''
  register method signs up new users
  '''
  username = input("Enter your preferred username: \n")
  password = input("Enter your preferred password: \n")
  passwordAgain = input("Enter the password again: \n")
  if(password == passwordAgain):
    new_user = createUser(username,password)
    saveUser(new_user)
    print(f'Welcome {username}')
    print("Please enter login details:")
    login()
  else:
    register()

  def createCredential(userAccount,userSite,password){
    '''
    createCredential method creates an instance of Credentials class
    '''
    newCred = Credentials(userAccount,userSite,password)
  }

  def saveCredential
  
  def menu():
    '''
    method menu displays options for accessing features 
    '''
    print("\n Pick a choice of what you would like to do: \nA:Add Credential with Custom Password \nB:Add Credential with Generated Password \nC:View all my credentials \nD:Delete some credentials")
    menu_choice = input()
    if(menu_choice == "A" or menu_choice == "a"):
      print("Please fill in the details below: \n")
      addCustomCredential()
    
    elif(menu_choice == "B" or menu_choice == "b"):
      print("Please fill in the details below and a password will be autogenerated for you: \n")
      addAutoCredential()
    
    elif(menu_choice == "C" or menu_choice =="c"):
      print("Here you go \n")
      Credentials.viewCredentials()
      leave = input("Enter 1 to exit")
      if(leave == "1"):
        menu()
    
    elif(menu_choice == "D" or menu_choice == "d"):
      print("From which site do you wish to delete credentials?\n")
      deleteCredentials()

def main():
  # print('')
  print("*"*40)
  print("Welcome to Password Locker \nHow may we assist you today?")
  print("\n A:Register \n B:Login \n C:Exit \n")
  first_choice = input()
  if(first_choice == "A" or first_choice == "a"):
    register()
  elif(first_choice == "B" or first_choice == "b"):
    login()
  elif(first_choice == "C" or first_choice =="c"):
    return 0
  
if __name__ == '__main__':
    main()